### ISSUE TITLE
Camera background permission check

### ISSUE THREAD

**Issue by tajchert** [tajchert/Nammu#3]
`Nammu.checkCamera()` is there but is kept private as this results in crash in sample app when Camera in Fragment is launched:

```
java.lang.RuntimeException: set display orientation failed
            at android.hardware.Camera.setDisplayOrientation(Native Method)
            at pl.tajchert.nammusample.camera.CameraPreview.surfaceChanged(CameraPreview.java:97)
            at android.view.SurfaceView.updateWindow(SurfaceView.java:591)
            at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2030)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
```

To fix this probably there is needed some release call or use of Camera2 API.
I couldn't find any method that doesn't open Camera preview and require permission to use a test (so only async methods which are not perfect).

For now Camera permission can be check only with Activity instance with new runtime permission API.

Help needed - if you know solution to that :)

**Comment by tajchert** [comment]
My mistake, it turned out that context has method to check permissions in easy manner. Deleted a two hour code, and also solved that issue.
